version: '3.3'
services:
  db: 
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'todolist_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db-mysql:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    ports:
      - '8081:80'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  my-db-mysql:
